# Homework 2 - balancing, transformations, and dimensionality reduction (deadline 22. 12. 2024, 23:59)

In short, the main task is to play with balancing, binning, transformations, and dimensionality reduction to obtain the best results for the binary classification task.
  
> The instructions are not given in detail: It is up to you to come up with ideas on how to fulfill the particular tasks as best you can!

However, we **strongly recommend and require** the following:
* Follow the assignment step by step. Number each step.
* Properly comment on all your steps. Use Markdown cells and visualizations. Comments are evaluated for 2 points of the total, together with the final presentation of the solution. However, it is not desirable to write novels! 
* This task is timewise and computationally intensive. Do not leave it to the last minute.
* Most steps contain the number of features that should be treated. You can preprocess more features. However, it does not mean the teacher will give you more points. Focus on quality, not quantity.
* Hand in a notebook that has already been run (i.e., do not delete outputs before handing in).

## What are you supposed to do:

  1. Download the dataset [here](https://www.dropbox.com/s/aq08ytozfplb97b/data.csv?dl=0). Split the dataset into a train, validation, and test set and **use these parts correctly (!)** in the following steps.
  1. Choose at least one classification algorithm whose performance is to be improved in the following steps.
  1. Use at least two binning methods (on features of your choice, with your choice of parameters) and comment on their effects on classification performance. _I.e., one kind of classifier trained for each binning and a comparison of the effect of binning methods against each other._ _(4 points, depends on creativity)_ 
  1. Use at least two data balancing techniques on the correct part of the dataset and comment on its effects on classification performance. Focus on the comparison of methods between each other. _I.e., one type of classifier trained for each balancing and a comparison of the effect of balancing methods against each other._ **Just copied code from tutorial four will not be accepted.** _(6 points, depends on creativity)_
  1. Transform the features appropriately and prepare new ones (i.e., feature engineering) - focus on the increase in the model's performance (possibly in combination with further steps). _(5 points, depends on creativity)_ 
  1. Try to find some suitable subset of features - use at least two feature selection methods. Evaluate your choice on the validation set and discuss the influence. Do not use PCA (principal component analysis) in this step. Manual selection will not be accepted. _(4 points, depends on creativity)_
  1. Use PCA to reduce the dimensionality. Discuss the influence of the number of principal components. _(4 points)_
  1. Try to find the best combination of the previous steps and run final classification tests on the correct part of the dataset - first for the original data, second for the best-found combination of the previous preprocessing steps. Compare the results and discuss (give a comment, use graphs, and so on). _(5 points)_

All your steps, choices, and the following code **must be commented on!** For text comments (discussion, etc., not code comments), use **Markdown cells**. Comments are evaluated for _2 points_ together with the final presentation of the solution.

**If you do all this properly, you will obtain 30 points.**

### FAQ

* Select the appropriate metric to evaluate the classification results.
* In steps 2 and 3, you are comparing methods against each other, not their effect on unadjusted data. However, you can comment on that, too.
* You choose the subset of features only in step 2 because of the binning methods. In the other steps, you work with the whole dataset.

## Comments

  * Please follow the technical instructions from https://courses.fit.cvut.cz/NI-PDD/homeworks/index.html.
  * Methods that are more complex and were not shown during the tutorials are considered more creative and should be described in detail.
  * English is not compulsory.

  
## Data description

* The dataset can be downloaded [here](https://www.dropbox.com/s/aq08ytozfplb97b/data.csv?dl=0).
* The data are devoted to the binary classification task. The aim is to predict the probability that a driver will initiate an auto insurance claim next year.
* The target feature is called 'y' and signifies whether or not a claim was filed for that policyholder.
* To fulfill the task, one does not need to know the meaning of predictors.
* Predictors that belong to similar groupings are tagged as such in the feature names (e.g., ind, reg, car, calc). In addition, feature names include the postfix _bin_ to indicate binary features and the postfix _cat_ to indicate categorical features. Features without these designations are either continuous or ordinal. Values of -1 indicate that the feature was missing from the observation.
* While using [train_test_split](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html), control the shuffling of data by random_state parameter. Do not use shuffle=False, probably never (can cause systematic error).

## Imports

In [3]:
import pandas as pd

dataset_path = 'data.csv'
rd_seed = 42

## First Data Inspection

In [4]:
df = pd.read_csv(dataset_path, low_memory=False)
df.head()

,y,xind_01,xind_02_cat,xind_03,xind_04_cat,xind_05_cat,xind_06_bin,xind_07_bin,xind_08_bin,xind_09_bin,...,xcalc_11,xcalc_12,xcalc_13,xcalc_14,xcalc_15_bin,xcalc_16_bin,xcalc_17_bin,xcalc_18_bin,xcalc_19_bin,xcalc_20_bin
0,0,2,1,5,1,6,0,1,0,0,...,4,0,2,8,0,0,0,1,1,0
1,0,2,1,6,0,0,0,0,0,1,...,9,2,3,7,0,0,1,0,0,0
2,0,2,1,9,0,0,1,0,0,0,...,5,0,2,6,0,1,0,1,1,0
3,0,1,1,6,0,0,1,0,0,0,...,3,0,4,8,0,0,1,0,0,0
4,0,1,1,5,1,0,0,1,0,0,...,4,3,1,2,0,1,0,0,1,0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 595212 entries, 0 to 595211
Data columns (total 58 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   y             595212 non-null  int64
 1   xind_01       595212 non-null  int64
 2   xind_02_cat   595212 non-null  int64
 3   xind_03       595212 non-null  int64
 4   xind_04_cat   595212 non-null  int64
 5   xind_05_cat   595212 non-null  int64
 6   xind_06_bin   595212 non-null  int64
 7   xind_07_bin   595212 non-null  int64
 8   xind_08_bin   595212 non-null  int64
 9   xind_09_bin   595212 non-null  int64
 10  xind_10_bin   595212 non-null  int64
 11  xind_11_bin   595212 non-null  int64
 12  xind_12_bin   595212 non-null  int64
 13  xind_13_bin   595212 non-null  int64
 14  xind_14       595212 non-null  int64
 15  xind_15       595212 non-null  int64
 16  xind_16_bin   595212 non-null  int64
 17  xind_17_bin   595212 non-null  int64
 18  xind_18_bin   595212 non-null  int64
 19  xreg_01       595212 non-null  float64
 20  xreg_02       595212 non-null  float64
 21  xreg_03       595212 non-null  float64
 22  xcar_01_cat   595212 non-null  int64
 23  xcar_02_cat   595212 non-null  int64
 24  xcar_03_cat   595212 non-null  int64
 25  xcar_04_cat   595212 non-null  int64
 26  xcar_05_cat   595212 non-null  int64
 27  xcar_06_cat   595212 non-null  int64
 28  xcar_07_cat   595212 non-null  int64
 29  xcar_08_cat   595212 non-null  int64
 30  xcar_09_cat   595212 non-null  int64
 31  xcar_10_cat   595212 non-null  int64
 32  xcar_11_cat   595212 non-null  int64
 33  xcar_11       595212 non-null  int64
 34  xcar_12       595212 non-null  float64
 35  xcar_13       595212 non-null  float64
 36  xcar_14       595212 non-null  float64
 37  xcar_15       595212 non-null  float64
 38  xcalc_01      595212 non-null  float64
 39  xcalc_02      595212 non-null  float64
 40  xcalc_03      595212 non-null  float64
 41  xcalc_04      595212 non-null  int64
 42  xcalc_05      595212 non-null  int64
 43  xcalc_06      595212 non-null  int64
 44  xcalc_07      595212 non-null  int64
 45  xcalc_08      595212 non-null  int64
 46  xcalc_09      595212 non-null  int64
 47  xcalc_10      595212 non-null  int64
 48  xcalc_11      595212 non-null  int64
 49  xcalc_12      595212 non-null  int64
 50  xcalc_13      595212 non-null  int64
 51  xcalc_14      595212 non-null  int64
 52  xcalc_15_bin  595212 non-null  int64
 53  xcalc_16_bin  595212 non-null  int64
 54  xcalc_17_bin  595212 non-null  int64
 55  xcalc_18_bin  595212 non-null  int64
 56  xcalc_19_bin  595212 non-null  int64
 57  xcalc_20_bin  595212 non-null  int64
dtypes: float64(10), int64(48)
memory usage: 263.4 MB

In [5]:
df.describe()

,y,xind_01,xind_02_cat,xind_03,xind_04_cat,xind_05_cat,xind_06_bin,xind_07_bin,xind_08_bin,xind_09_bin,...,xcalc_11,xcalc_12,xcalc_13,xcalc_14,xcalc_15_bin,xcalc_16_bin,xcalc_17_bin,xcalc_18_bin,xcalc_19_bin,xcalc_20_bin
count,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,...,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000
mean,0.036448,1.900378,1.358943,4.423318,0.416794,0.405188,0.393742,0.257033,0.163921,0.185304,...,5.441382,1.441918,2.872288,7.539026,0.122427,0.627840,0.554182,0.287182,0.349024,0.153318
std,0.187401,1.983789,0.664594,2.699902,0.493311,1.350642,0.488579,0.436998,0.370205,0.388544,...,2.332871,1.202963,1.694887,2.746652,0.327779,0.483381,0.497056,0.452447,0.476662,0.360295
min,0.000000,0.000000,-1.000000,0.000000,-1.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.000000,1.000000,2.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,1.000000,1.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,5.000000,1.000000,3.000000,7.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000
75%,0.000000,3.000000,2.000000,6.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,...,7.000000,2.000000,4.000000,9.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000
max,1.000000,7.000000,4.000000,11.000000,1.000000,6.000000,1.000000,1.000000,1.000000,1.000000,...,19.000000,10.000000,13.000000,23.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000